name: transcendence

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   image: nginx
  #   container_name: nginx
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - static:/var/www/html
  #   networks:
  #     - transcendence
  #   restart: unless-stopped

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    image: django
    container_name: django
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DJANGO_SUPERUSER_PASSWORD: admin_password
    ports:
      - "9000:9000"
    networks:
      - transcendence
    volumes:
      - django_app:/usr/src/app
      - static:/usr/src/static/
    # depends_on:
    #   - postgres
    restart: unless-stopped

# postgres:
#   image: postgres:16.4-alpine3.20
#   container_name: postgres
#   env_file:
#     - .env
#   environment:
#     POSTGRES_USER: hello # ${POSTGRES_USER}
#     POSTGRES_PASSWORD: hellopwd # ${POSTGRES_PASSWORD}
#     POSTGRES_DB: hellodb # ${POSTGRES_DB}
#     LC_COLLATE: en_US.UTF-8
#     LC_CTYPE: en_US.UTF-8
#   expose:
#     - 5432
#   volumes:
#     - postgres_data:/var/lib/postgresql/data
#   networks:
#     - transcendence
#   restart: unless-stopped

volumes:
  static:
    name: static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/static
  django_app:
    name: django_app
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/django_app/
  # postgres_data:
  #   name: postgres_data
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ../volumes/postgres_data/

networks:
  transcendence:
    name: transcendence
    driver: bridge
