name: transcendence

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - static:/var/www/html
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    volumes:
      - static:/data
    networks:
      - transcendence

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    image: django
    container_name: django
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - transcendence
    volumes:
      - django_app:/usr/src/app
      # - ./django:/usr/src/app
      - static:/app/static/
    restart: unless-stopped

volumes:
  static:
    name: static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/static
  django_app:
    name: django_app
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/django_app/

networks:
  transcendence:
    name: transcendence
    driver: bridge
