name: transcendence

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   image: nginx
  #   container_name: nginx
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - static:/var/www/html
  #   networks:
  #     - transcendence
  #   restart: unless-stopped

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gateway
    image: gateway
    container_name: gateway
    environment:
      - PYTHONPATH=/usr/src/app/authentif_app
    #   - DATABASE_URL=postgres://user:password@postgres:5432/mydb
    env_file:
      - .env
    ports:
      - "8443:8443"
    networks:
      - transcendence
    volumes:
      - backend:/usr/src/app
      - frontend:/usr/src/frontend/
    depends_on:
      - postgres
      - authentif
    # command:
    #   - daphne
    #   - -e
    #   - ssl:8443:/etc/ssl/certs/key.pem:/etc/ssl/certs/cert.pem
    #   - gateway.asgi:application
    command: uvicorn gateway.asgi:application --host 0.0.0.0 --port 8443 --reload --ssl-keyfile=/usr/src/app/key.pem --ssl-certfile=/usr/src/app/cert.pem
    # command: gunicorn gateway.asgi:application -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8443 --ssl-keyfile=/usr/src/app/key.pem --ssl-certfile=/usr/src/app/cert.pem # to handle multiple connections
    # restart: unless-stopped

  authentif:
    build:
      context: ./authentif
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: authentif
    image: authentif
    container_name: authentif
    #   - DATABASE_URL=postgres://user:password@postgres:5432/mydb
    env_file:
      - .env
    expose:
      - 9001
    networks:
      - transcendence
    volumes:
      - backend:/usr/src/app
      - frontend:/usr/src/frontend/
    depends_on:
      - postgres
    command: uvicorn authentif.asgi:application --host 0.0.0.0 --port 9001 --reload --ssl-keyfile=/usr/src/app/key.pem --ssl-certfile=/usr/src/app/cert.pem
  #   restart: unless-stopped

  profileapi:
    build:
      context: ./profileapi
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: profileapi
    image: profileapi
    container_name: profileapi
    #   - DATABASE_URL=postgres://user:password@postgres:5432/mydb
    env_file:
      - .env
    expose:
      - 9002
    networks:
      - transcendence
    volumes:
      - backend:/usr/src/app
      - frontend:/usr/src/frontend/
    depends_on:
      - postgres
      - authentif
    command: uvicorn profileapi.asgi:application --host 0.0.0.0 --port 9002 --reload --ssl-keyfile=/usr/src/app/key.pem --ssl-certfile=/usr/src/app/cert.pem

  gamecalc:
    build:
      context: ./gamecalc
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gamecalc
    image: gamecalc
    container_name: gamecalc
    #   - DATABASE_URL=postgres://user:password@postgres:5432/mydb
    env_file:
      - .env
    expose:
      - 9003
    networks:
      - transcendence
    volumes:
      - backend:/usr/src/app
      - frontend:/usr/src/frontend/
    depends_on:
      - postgres
      - authentif
    command: uvicorn gamecalc.asgi:application --host 0.0.0.0 --port 9003 --reload --ssl-keyfile=/usr/src/app/key.pem --ssl-certfile=/usr/src/app/cert.pem

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    env_file:
      - .env
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
    expose:
      - 5432
    working_dir: /var/lib/postgresql/data
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - transcendence
    # restart: unless-stopped

volumes:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/frontend
  backend:
    name: backend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/backend/
  postgres_db:
    name: postgres_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/postgres_db/

networks:
  transcendence:
    name: transcendence
    driver: bridge
