name: transcendence

services:
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   image: nginx
  #   container_name: nginx
  #   env_file:
  #     - .env
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - static:/var/www/html
  #   networks:
  #     - transcendence
  #   restart: unless-stopped

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: gateway
    image: gateway
    container_name: gateway
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - transcendence
    volumes:
      - backend:/usr/src/app
      - frontend:/usr/src/frontend/
    depends_on:
      - postgres
  #   - authuser
  # restart: unless-stopped

  # authuser:
  #   build:
  #     context: ./authuser
  #     dockerfile: Dockerfile
  #   image: authuser
  #   container_name: authuser
  #   env_file:
  #     - .env
  #   ports:
  #     - "9001:9000"
  #   networks:
  #     - transcendence
  #   volumes:
  #     - backend:/usr/src/app
  #     - frontend:/usr/src/frontend/
  #   # depends_on:
  #   #   - postgres
  #   restart: unless-stopped

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    env_file:
      - .env
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
    expose:
      - 5432
    working_dir: /var/lib/postgresql/data
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - transcendence
    # restart: unless-stopped

volumes:
  frontend:
    name: frontend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/frontend
  backend:
    name: backend
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/backend/
  postgres_db:
    name: postgres_db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/postgres_db/

networks:
  transcendence:
    name: transcendence
    driver: bridge
